Traceback (most recent call last):
  File "c:\Users\soham\Automated-renal-compartment-segmentation-of-the-kidneys\main.py", line 43, in <module>
    model = create_model(input_shape, config['model']['learning_rate'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\soham\Automated-renal-compartment-segmentation-of-the-kidneys\src\models\models.py", line 4, in create_model
    model = U_Net(input_shape)
            ^^^^^^^^^^^^^^^^^^
  File "c:\Users\soham\Automated-renal-compartment-segmentation-of-the-kidneys\src\models\unet.py", line 36, in U_Net
    input1 = Input(Image_Size)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\soham\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\soham\anaconda3\Lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 217, in __init__
    raise TypeError(
TypeError: Dimension value must be integer or None or have an __index__ method, got value ''('' with type '<class 'str'>'